### PR TITLE
add name and type to composer.json

### PR DESCRIPTION
**Pull request by michield**
I'm trying to create a method to package phpList with composer. To pull in plugins, they need to have a name and the type "phplist-plugin".

### CODE REVIEW

**Comment by bramley** [comment]
When composer processes this composer.json it might try to install upgraded packages based on the require
```
    "require": {
        "chdemko/bitarray": "1.0.0",
        "jasongrimes/paginator": "1.0.2",
        "jdorn/sql-formatter": "^1.2",
        "jmathai/php-multi-curl": "dev-master",
        "katzgrau/klogger": "1.2.0",
        "mouf/picotainer": "1.1.0",
        "pelago/emogrifier": "^3.1",
        "psr/log": "1.0.0",
        "symfony/css-selector": "^3.0",
        "symfony/filesystem": "3.4"
    },
```
Is there any indication of that happening? Most of these are either not actively changing, so there won't be a later version, or I have fixed a version (e.g. 1.1.0).

**Comment by bramley** [comment]
Thinking about this a bit more, I don't think that plugins are dependencies for phplist, unlike say phpmailer, but are just fairly independent packages that can be pulled in. Just retrieving and expanding the GitHub zip file for a plugin seems simple enough.

Using Composer for plugins will probably change the directory structure, I don't think it will be as simple as admin/plugins/myplugin.php etc.

**Comment by michield** [comment]
Yes, but I'm trying to simplify the creation of a version, and was wondering how useful composer can be for that.

See https://github.com/phpList/phplist3/commit/0eb822ebb40bdec2ae008f3085812bf9c9965d77

If you run "composer update --no-dev" on that, it will install the theme, info, help, and some plugins

It's slightly clumsy the way the plugins are installed, but it may work.

A better option would be to add an "installer" for phpList to composer: https://github.com/composer/installers

But I'm not sure we're big enough for that, although phpBB is there as well.
But adding "type: phplist-plugin" to composer.json will work either way.

**Comment by michield** [comment]
Sorry, I meant to give this commit

https://github.com/michield/phplist3/commit/63153ece437ed57c5e175886cd579bcf9569e896

**Comment by bramley** [comment]
I installed your branch and now see how you are trying to build a new version.

The Composer plugin approach looks pretty complex to me. An alternative approach is to install/upgrade the plugins within phplist itself as part of an installation or an upgrade. Move the bulk of the plugin installation code that is in the plugins.php page into a function that can be called from elsewhere. I fiddled around with that yesterday and it seemed to work ok for an upgrade.

I will commit your change but use "bramley/phplist-plugin-common" as the name.

**Comment by michield** [comment]
Thanks. I'm rebuilding the release build process, which currently is a very complex shell script, that pulls in all the repos and puts them in the correct place. Yes, I'm not entirely sure this is going to work for plugins, but I'll give it a try.

**Pull request closed without merging**
