### PR TITLE
update dependency for PHP8 compatibility

### PR DESCRIPTION
**Pull request by michield**
The dependencies fail on PHP8 with the following error

```
Updating dependencies     
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pelago/emogrifier[v3.1.0, ..., 3.1.x-dev] require php ^5.6 || ~7.0 || ~7.1 || ~7.2 || ~7.3 || ~7.4 -> your php version (8.0.13) does not satisfy that requirement.
    - bramley/phplist-plugin-common dev-master requires pelago/emogrifier ^3.1 -> satisfiable by pelago/emogrifier[v3.1.0, 3.1.x-dev].
    - Root composer.json requires bramley/phplist-plugin-common dev-master -> satisfiable by bramley/phplist-plugin-common[dev-master].

```

updating to version 6.0 resolves that.

### CODE REVIEW

**Comment by michield** [comment]
Hmm, maybe we need to go down to 5.0

this seems to break 7.3 which is still in support

**Comment by bramley** [comment]
I will need to look into this because my recollection is that emogrifer 6.0 has dependencies which are not guaranteed to be met. such as php 7.2 or later. Can you try running this with an older php version, even maybe 5.6 which is my currently documented minimum version for using this plugin.

This failure is a bit false though, because php 8 didn't exist when emogrifier 3.1 was released, there shouldn't be any problem with using that version with php 8.

But I don't understand the process that you are running. I thought that you would just pull-in the latest version of each plugin. My own build process should ensure that the composer constraints are met.

**Comment by bramley** [comment]
>This failure is a bit false though, because php 8 didn't exist when emogrifier 3.1 was released, there shouldn't be any problem with using that version with php 8.

What I mean is that this is a problem with building using php 8, not actually running the code with php 8.

**Comment by michield** [comment]
Yes, the main reason is to make it pass on PHP8. The CI in main phpList runs it through all versions that are supported, but PHP8 fails: https://github.com/phpList/phplist3/actions/runs/1510833283

I will look into a way to have a different composer.lock file per PHP version

**Comment by michield** [comment]
ok, with 5.0 it passes on all the relevant versions. https://github.com/michield/phplist3/runs/4342390411?check_suite_focus=true

> This failure is a bit false though, because php 8 didn't exist when emogrifier 3.1 was released, there shouldn't be any problem with using that version with php 8.

Well, that's not necessarily true. The code may no longer work on PHP8, which is why this dependency system exists. The maintainers or the code released new versions to handle PHP8. Depends a bit on how much you use this code in your plugin, but presumably some parts could fail.

**Pull request closed without merging**
